services:
  app:
    build: .
    container_name: app
    ports:
      - "8080:8080"
    environment:
      - driverClassName=org.sqlite.JDBC
      - url=jdbc:sqlite:memory:myDb?cache=shared
      - username=sa
      - password=sa
      - spring.jpa.database-platform=org.hibernate.community.dialect.SQLiteDialect
      - hibernate.hbm2ddl.auto=create-drop
      - hibernate.show_sql=true
    volumes:
      - ./data:/app